<?php

require_once '../application/libraries/NotificationTypeFactory.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-27 at 12:22:36.
 */
class NotificationTypeFactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var NotificationTypeFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NotificationTypeFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers NotificationTypeFactory::getNotificationTypeById
     */
    public function testGetNotificationTypeById() {
        $notifType = $this->object->getNotificationTypeById(1);
        $this->assertTrue(is_object($notifType));
        $this->assertTrue($notifType->getId() == 1);
        $this->assertTrue($notifType->getName() == "Lights left on");
    }

    /**
     * @covers NotificationTypeFactory::createObjectFromData
     * @todo   Implement testCreateObjectFromData().
     */
//    public function testCreateObjectFromData() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

}
